### ISSUE TITLE
Problems with build stage of SoapySDR

### ISSUE THREAD

**Issue by G4DCP** [PlutoSDR/plutosdr-bsp#2]
I can't get a successful build as I hit problems with -

[ 94%] Building CXX object python3/CMakeFiles/_SoapySDR3.dir/SoapySDRPYTHON_wrap.cxx.o
arm-xilinx-linux-gnueabi-g++: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/include/python3.5m'
python3/CMakeFiles/_SoapySDR3.dir/build.make:70: recipe for target 'python3/CMakeFiles/_SoapySDR3.dir/SoapySDRPYTHON_wrap.cxx.o' failed
make[4]: *** [python3/CMakeFiles/_SoapySDR3.dir/SoapySDRPYTHON_wrap.cxx.o] Error 1
make[4]: Leaving directory '/home/pdh/installs/plutosdr-bsp/buildroot/output/build/soapysdr-0.6.0'
CMakeFiles/Makefile2:470: recipe for target 'python3/CMakeFiles/_SoapySDR3.dir/all' failed
make[3]: *** [python3/CMakeFiles/_SoapySDR3.dir/all] Error 2
make[3]: *** Waiting for unfinished jobs....
[ 97%] Linking CXX shared module _SoapySDR.so
make[4]: Leaving directory '/home/pdh/installs/plutosdr-bsp/buildroot/output/build/soapysdr-0.6.0'
[ 97%] Built target _SoapySDR
make[3]: Leaving directory '/home/pdh/installs/plutosdr-bsp/buildroot/output/build/soapysdr-0.6.0'
Makefile:138: recipe for target 'all' failed
make[2]: *** [all] Error 2

How does one work around this? Don't really need the python3 stuff but not sure how to suppress it.

Peter G4DCP

**Comment by jocover** [comment]
temporary solution add `SOAPYSDR_CONF_OPT = -DENABLE_PYTHON=OFF` on soapysdr.mk file

**Comment by G4DCP** [comment]
This file exists in two locations one is in pakages  the other is in  buildroot/package.
I am trying both. I get an error message saying that it should be OPTS instead of OPT. Trying that.
Failed identically now trying make clean - make to see if that helps. Obviously it will be some time before the build completes I will let you know how it go's
-Peter

**Comment by G4DCP** [comment]
Can now confirm it builds from a make clean - make attempt.

Thanks
